#Can be improved by providing  error specifications and setting up controller code generation
openapi: 3.0.0
info:
  title: The API of the account funds application
  version: 1.0.0
paths:
  /api/v1/transfers:
    post:
      description: Add a transfer from one account to another
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./schemas/funds-transfer-request.schema.json
            example: |
              {
              	"operationId": "b19d837f-2b85-4ec6-8c57-3a83cae34139 ",
              	"accounts": {
              		"from": {
              			"id": "48e3d142-e5d6-442a-bf61-42c3e5673700"
              		},
              		"to": {
              			"id": "a27fa283-f638-49d1-b150-8adf065c80e2"
              		}
              	},
              	"amount": {
              		"value": "90.05",
              		"currency": "EUR"
              	},
              	"message": "Test transfer"
              }
      responses:
        200:
          description: Successful transfer response
          content:
            application/json:
              schema:
                type: object
                $ref: ./schemas/funds-transfer-response.schema.json
              example: |
                {
                  "status": "OK",
                  "transferNumber": "1",
                  "createdAt": "2019-12-01T13:29:20.561374"
                }
        400:
          description: Invalid request data error
          content:
            application/json:
              schema:
                type: object
                $ref: ./schemas/error-response.schema.json
              example: |
                {
                  "message": "transferRequest.amount.value: must match \"^\\d{1,13}\\.\\d\\d$\"",
                }
        404:
          description: Not found error
          content:
            application/json:
              schema:
                type: object
                $ref: ./schemas/error-response.schema.json
              example: |
                {
                  "message": "Account funds for account 48e3d142-e5d6-442a-bf61-42c3e5673700 weren't found"
                }
        409:
          description: Another transfer with the same operationId exists error
          content:
            application/json:
              schema:
                type: object
                $ref: ./schemas/error-response.schema.json
              example: |
                {
                  "message": "A transfer with operation ID b19d837f-2b85-4ec6-8c57-3a83cae34139 already exists"
                }
  /health:
    200:
      description: Health check
      content:
        application/json:
          example: |
            {
              "status": "UP"
            }